- id: dependency-graph
  name: dependency-graph
  description: "dependency-graph: Gaining insight in your repositories"
  entry: dependency_graph
  language: python
  language_version: python3
  minimum_pre_commit_version: 3.7
  require_serial: true
