repos:
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
    - id: black
      language_version: python3.7
- repo: https://github.com/pycqa/isort
  rev: 5.6.4
  hooks:
    - id: isort
      name: isort (python)
      args: ["--profile", "black"]
